name: smart_farm
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # third-party lib
  # getX
  get:
  flutter_localizations:
    sdk: flutter
  syncfusion_localizations: ^22.2.12
  flutter_phoenix: ^1.1.1
  get_storage: ^2.1.1 

  # get picture
  camera: ^0.10.5+9
  image_picker: ^0.8.4+3

  # connect
  path_provider: ^2.1.2
  path: ^1.8.3
  http: ^1.1.0
  dio: ^5.4.1

  # others
  cupertino_icons: ^1.0.2
  loading_animation_widget: ^1.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
